### ISSUE TITLE
Async plugins

### ISSUE THREAD

**Issue by paulmillr** [reworkcss/rework#183]
Dupe of #2 but I got an actual API proposition

What about this

``` javascript
// sync
rework(css).use(plugin).toString()

// async; promise-based
rework(css)
  .then(function(object) {
    return plugin(object);
  })
  .then(function(object) {
    return object.toString();
  })

// or similar
```

@necolas

**Comment by paulmillr** [comment]
tired of shitty performance of synchronous FS calls — this would really help in case of `@import`s etc

**Comment by RobLoach** [comment]
Just sticking your PR in here so people can follow along: https://github.com/reworkcss/rework/pull/185
